conf.yaml, otherdave/__main__.py
=> Add quiet command

conf.yaml, otherdave/commands/mimic.py
=> Variable mimic length

conf.yaml, otherdave/__main__.py, otherdave/commands/__init__.py, otherdave/commands/memory.py
Can now save messages and parrot them back later. Will parrot periodically if things are quiet.
=> Add remember, forget, and parrot

.github/workflows/python-app.yml
Tests run on PR and you can't push to master - no reason to run them a second time.
=> Remove test on push

conf.yaml
Reflecting addition of memory commands
=> Rev version

conf.yaml, otherdave/commands/memory.py, otherdave/util/triggers.py
Respond to !remember command with emote on success, rather than text confirmation
=> Remember Brain

conf.yaml
Probability is easy until you think about it.
=> Bump parrot interval

otherdave/commands/memory.py
Probability remains hard even after you try to understand it.
=> Update squawk probability function

otherdave/commands/mimic.py
Reverts ibanner56/OtherDave#89
=> Revert "Update mimic.py"

requirements.txt
Grab bugfix, jump to latest version.
=> Rev Discord.py version

conf.yaml, otherdave/__main__.py
* addresses #93 
* fixes some command naming and ordering
* adds github link to help text
=> Only mention MercWorks and other small fixes

conf.yaml, data/madlib/templates.json, otherdave/__main__.py, otherdave/commands/__init__.py, otherdave/commands/give.py, otherdave/util/madlib.py
Add inventory to OtherDave, allow users to give and take things
=> Add inventory and give commands

conf.yaml
Rev the version post-merge like a trash panda
=> Someone forgot to rev the version whee

conf.yaml, otherdave/__main__.py, otherdave/commands/give.py
Adds smaller user inventories
Makes OD resistant to giving up things he's just acquired unless they're selected at random
=> Create user inventories, make OD greedy

otherdave/commands/give.py
Last item type PR for a bit I SWEAR
=> Bold-face items in bot messages

conf.yaml, otherdave/commands/prompt.py
=> Quick fix to add responses to prompt additions

otherdave/commands/prompt.py
One day I'll check something in that's right the first time.
=> Woo whitespace

otherdave/__main__.py, otherdave/commands/drunkdraw.py, otherdave/commands/give.py, otherdave/commands/haiku.py, otherdave/commands/haunt.py, otherdave/commands/ignore.py, otherdave/commands/jabber.py, otherdave/commands/memory.py, otherdave/commands/mimic.py, otherdave/commands/recommend.py, otherdave/util/__init__.py, otherdave/util/config.py, otherdave/util/constants.py, otherdave/util/stringmischief.py, otherdave/util/triggers.py, otherdave/util/unflect.py, setup.py, test/commands/test_haiku.py
Move string constants and config values into util files to save space and improve reusability.
=> Clean up string constants and configuration access

otherdave/commands/give.py
=> Fix same bug in use that was in drop

otherdave/__main__.py, otherdave/commands/jabber.py
I swear to god, Python, it's like you're trying to sabotage me intentionally.
=> Clean up two more ambiguous references

conf.yaml, otherdave/__main__.py, otherdave/commands/give.py, otherdave/commands/haiku.py, otherdave/commands/haunt.py, otherdave/commands/ignore.py, otherdave/commands/memory.py, otherdave/commands/mimic.py, otherdave/commands/prompt.py, otherdave/commands/recommend.py, otherdave/commands/respect.py, otherdave/util/config.py, otherdave/util/constants.py, otherdave/util/triggers.py
360 noscope bug-free slam dunk lets go
=> Switch from "!" commands to native discord app commands

conf.yaml, otherdave/__main__.py, otherdave/commands/mimic.py
=> Add mock context menu command

otherdave/__main__.py
=> Add cooldown to mock

otherdave/util/stringmischief.py
=> Address byte length and signing bugs

data/units.json
=> Add more kinds of units

conf.yaml, otherdave/__main__.py, otherdave/commands/give.py, otherdave/commands/haiku.py, otherdave/commands/haunt.py, otherdave/commands/horoscope.py, otherdave/commands/ignore.py, otherdave/commands/jabber.py, otherdave/commands/memory.py, otherdave/commands/mimic.py, otherdave/commands/prompt.py, otherdave/commands/recommend.py, otherdave/commands/respect.py, otherdave/commands/spend.py, otherdave/util/dlog.py, otherdave/util/madlib.py, otherdave/util/pickledbrg.py, otherdave/util/stringmischief.py, otherdave/util/triggers.py
Update everything to clean up function signatures and clarify parameter types.
=> Add parameter and return types to all function signatures
